package io.github.w33vit.mystories.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import io.github.w33vit.mystories.dao.Stories;

import io.github.w33vit.mystories.dao.StoriesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storiesDaoConfig;

    private final StoriesDao storiesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storiesDaoConfig = daoConfigMap.get(StoriesDao.class).clone();
        storiesDaoConfig.initIdentityScope(type);

        storiesDao = new StoriesDao(storiesDaoConfig, this);

        registerDao(Stories.class, storiesDao);
    }
    
    public void clear() {
        storiesDaoConfig.getIdentityScope().clear();
    }

    public StoriesDao getStoriesDao() {
        return storiesDao;
    }

}
