package io.github.w33vit.mystories.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.parceler.Parcel;
import org.parceler.ParcelConstructor;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * Entity mapped to table "STORIES".
 */
@Parcel(Parcel.Serialization.BEAN)
public class Stories {

    private Long id;
    private String title;
    private String content;
    private java.util.Date stories_date;

    public Stories() {
    }

    public Stories(String title, String content) {
        setTitle(title);
        setContent(content);
        setStories_date(null);
    }

    @ParcelConstructor
    public Stories(Long id, String title, String content, java.util.Date stories_date) {
        setId(id);
        setTitle(title);
        setContent(content);
        setStories_date(stories_date);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getStories_date() {
        return stories_date;
    }

    public void setStories_date(java.util.Date stories_date) {
        if (stories_date == null)
            stories_date = new Date();
        this.stories_date = stories_date;
    }

    public String getRealDate() {
        String realDate = new SimpleDateFormat("d MMM yyyy").format(stories_date);
        return realDate;
    }

}
